
name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "prune-image-versions" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - 'README.md'
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  delete-untagged-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Delete untagged versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'cmm262-notebook'
          package-type: 'container'
          min-versions-to-keep: 30
          ignore-versions:
            - programming-R
            - stats
            - rna-seq
            - scrna-seq
            - networks
            - chipseq
            - gwas
            - imgproc
            - popgen
            - spatial-tx
            - variant_calling
            - pr-15

