name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. 

on: 
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - '*.yaml'
  pull_request:
    branches: [ "*" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - 'README.md'
      - '*.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  multi-state-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ['build', 'release']
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to the Container registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Prune system
      - name: Prune
        run: docker system prune -af

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          multi-state-build: true 
          stages:
            - 'build'
            - 'release'
          build-args-per-stage:
            build:
              - CONTINUUMIO_MINICONDA_VERSION=latest
            release:
              - CONTINUUMIO_MINICONDA_VERSION=stable
          auto-prune: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
