name: Docker Image CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ucsdets/cmm262-notebook:$GITHUB_REF_NAME
    
    # https://github.com/docker/metadata-action
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push to Dockerhub
      run: docker push ucsdets/cmm262-notebook:$GITHUB_REF_NAME
